site_name: AWS Certified Data Analytics Specialty - Concept Notes
repo_url: https://github.com/jeyabalajis/aws-certified-data-analytics-specialty-notes.git
theme:
  name: 'material'
  logo: 'images/logo.png'
use_directory_urls: false
markdown_extensions:
  - admonition
  - pymdownx.details
  - codehilite
  - pymdownx.superfences
plugins:
    - search
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
nav:
  - Home: index.md
  - Collection:
      - Collection: collection/collection.md
      - Kinesis Data Firehose: collection/kinesis_data_firehose.md
      - Kinesis Data Streams: collection/kinesis_data_streams.md
      - Glue ETL: collection/glue_etl.md
      - Dynamo DB Streams: collection/dynamodb_streams.md
      - Database Migration Service: collection/database_migration_service.md
  - Processing:
      - Processing: processing/processing.md
      - Athena: processing/athena.md 
      - Amazon EMR: processing/amazon_emr.md
      - Glue: processing/glue.md
      - AWS IOT: processing/aws_iot.md
  - Storage:
      - Storage: storage/storage.md
  - Visualization:
      - Visualization: visualization/visualization.md
      - Quicksight: visualization/quick_sight.md
      - Open Search: visualization/open_search.md
  - Exam Preparation:
      - Exam Preparation: exam_prep/exam_preparation.md 